//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace EDDP2.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FooPortBinding", Namespace="http://com/")]
    public partial class Foo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback receiveMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendCarritoGraphOperationCompleted;
        
        private System.Threading.SendOrPostCallback valUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendProdCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendProdNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendProdBrandOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendProdPriceOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendProdImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendWhishOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendCartInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeFromWhishOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeFromCartOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendArbolBOperationCompleted;
        
        private System.Threading.SendOrPostCallback saleOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendHashGraphOperationCompleted;
        
        private System.Threading.SendOrPostCallback report1OperationCompleted;
        
        private System.Threading.SendOrPostCallback report2OperationCompleted;
        
        private System.Threading.SendOrPostCallback report3OperationCompleted;
        
        private System.Threading.SendOrPostCallback graphAvlTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback graphAdListOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendWhishGraphOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Foo() {
            this.Url = global::EDDP2.Properties.Settings.Default.EDDP2_WebReference_Foo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event receiveMessageCompletedEventHandler receiveMessageCompleted;
        
        /// <remarks/>
        public event sendCarritoGraphCompletedEventHandler sendCarritoGraphCompleted;
        
        /// <remarks/>
        public event valUserCompletedEventHandler valUserCompleted;
        
        /// <remarks/>
        public event sendProdCodeCompletedEventHandler sendProdCodeCompleted;
        
        /// <remarks/>
        public event SendProdNameCompletedEventHandler SendProdNameCompleted;
        
        /// <remarks/>
        public event sendProdBrandCompletedEventHandler sendProdBrandCompleted;
        
        /// <remarks/>
        public event sendProdPriceCompletedEventHandler sendProdPriceCompleted;
        
        /// <remarks/>
        public event sendProdImageCompletedEventHandler sendProdImageCompleted;
        
        /// <remarks/>
        public event sendWhishCompletedEventHandler sendWhishCompleted;
        
        /// <remarks/>
        public event sendCartInfoCompletedEventHandler sendCartInfoCompleted;
        
        /// <remarks/>
        public event removeFromWhishCompletedEventHandler removeFromWhishCompleted;
        
        /// <remarks/>
        public event removeFromCartCompletedEventHandler removeFromCartCompleted;
        
        /// <remarks/>
        public event sendArbolBCompletedEventHandler sendArbolBCompleted;
        
        /// <remarks/>
        public event saleCompletedEventHandler saleCompleted;
        
        /// <remarks/>
        public event sendHashGraphCompletedEventHandler sendHashGraphCompleted;
        
        /// <remarks/>
        public event report1CompletedEventHandler report1Completed;
        
        /// <remarks/>
        public event report2CompletedEventHandler report2Completed;
        
        /// <remarks/>
        public event report3CompletedEventHandler report3Completed;
        
        /// <remarks/>
        public event graphAvlTreeCompletedEventHandler graphAvlTreeCompleted;
        
        /// <remarks/>
        public event graphAdListCompletedEventHandler graphAdListCompleted;
        
        /// <remarks/>
        public event searchProductCompletedEventHandler searchProductCompleted;
        
        /// <remarks/>
        public event sendWhishGraphCompletedEventHandler sendWhishGraphCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string receiveMessage([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string message) {
            object[] results = this.Invoke("receiveMessage", new object[] {
                        message});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void receiveMessageAsync(string message) {
            this.receiveMessageAsync(message, null);
        }
        
        /// <remarks/>
        public void receiveMessageAsync(string message, object userState) {
            if ((this.receiveMessageOperationCompleted == null)) {
                this.receiveMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreceiveMessageOperationCompleted);
            }
            this.InvokeAsync("receiveMessage", new object[] {
                        message}, this.receiveMessageOperationCompleted, userState);
        }
        
        private void OnreceiveMessageOperationCompleted(object arg) {
            if ((this.receiveMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.receiveMessageCompleted(this, new receiveMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendCarritoGraph([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user) {
            object[] results = this.Invoke("sendCarritoGraph", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendCarritoGraphAsync(string user) {
            this.sendCarritoGraphAsync(user, null);
        }
        
        /// <remarks/>
        public void sendCarritoGraphAsync(string user, object userState) {
            if ((this.sendCarritoGraphOperationCompleted == null)) {
                this.sendCarritoGraphOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendCarritoGraphOperationCompleted);
            }
            this.InvokeAsync("sendCarritoGraph", new object[] {
                        user}, this.sendCarritoGraphOperationCompleted, userState);
        }
        
        private void OnsendCarritoGraphOperationCompleted(object arg) {
            if ((this.sendCarritoGraphCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendCarritoGraphCompleted(this, new sendCarritoGraphCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int valUser([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string pass) {
            object[] results = this.Invoke("valUser", new object[] {
                        user,
                        pass});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void valUserAsync(string user, string pass) {
            this.valUserAsync(user, pass, null);
        }
        
        /// <remarks/>
        public void valUserAsync(string user, string pass, object userState) {
            if ((this.valUserOperationCompleted == null)) {
                this.valUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalUserOperationCompleted);
            }
            this.InvokeAsync("valUser", new object[] {
                        user,
                        pass}, this.valUserOperationCompleted, userState);
        }
        
        private void OnvalUserOperationCompleted(object arg) {
            if ((this.valUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.valUserCompleted(this, new valUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendProdCode() {
            object[] results = this.Invoke("sendProdCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendProdCodeAsync() {
            this.sendProdCodeAsync(null);
        }
        
        /// <remarks/>
        public void sendProdCodeAsync(object userState) {
            if ((this.sendProdCodeOperationCompleted == null)) {
                this.sendProdCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendProdCodeOperationCompleted);
            }
            this.InvokeAsync("sendProdCode", new object[0], this.sendProdCodeOperationCompleted, userState);
        }
        
        private void OnsendProdCodeOperationCompleted(object arg) {
            if ((this.sendProdCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendProdCodeCompleted(this, new sendProdCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SendProdName() {
            object[] results = this.Invoke("SendProdName", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendProdNameAsync() {
            this.SendProdNameAsync(null);
        }
        
        /// <remarks/>
        public void SendProdNameAsync(object userState) {
            if ((this.SendProdNameOperationCompleted == null)) {
                this.SendProdNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendProdNameOperationCompleted);
            }
            this.InvokeAsync("SendProdName", new object[0], this.SendProdNameOperationCompleted, userState);
        }
        
        private void OnSendProdNameOperationCompleted(object arg) {
            if ((this.SendProdNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendProdNameCompleted(this, new SendProdNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendProdBrand() {
            object[] results = this.Invoke("sendProdBrand", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendProdBrandAsync() {
            this.sendProdBrandAsync(null);
        }
        
        /// <remarks/>
        public void sendProdBrandAsync(object userState) {
            if ((this.sendProdBrandOperationCompleted == null)) {
                this.sendProdBrandOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendProdBrandOperationCompleted);
            }
            this.InvokeAsync("sendProdBrand", new object[0], this.sendProdBrandOperationCompleted, userState);
        }
        
        private void OnsendProdBrandOperationCompleted(object arg) {
            if ((this.sendProdBrandCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendProdBrandCompleted(this, new sendProdBrandCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendProdPrice() {
            object[] results = this.Invoke("sendProdPrice", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendProdPriceAsync() {
            this.sendProdPriceAsync(null);
        }
        
        /// <remarks/>
        public void sendProdPriceAsync(object userState) {
            if ((this.sendProdPriceOperationCompleted == null)) {
                this.sendProdPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendProdPriceOperationCompleted);
            }
            this.InvokeAsync("sendProdPrice", new object[0], this.sendProdPriceOperationCompleted, userState);
        }
        
        private void OnsendProdPriceOperationCompleted(object arg) {
            if ((this.sendProdPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendProdPriceCompleted(this, new sendProdPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendProdImage() {
            object[] results = this.Invoke("sendProdImage", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendProdImageAsync() {
            this.sendProdImageAsync(null);
        }
        
        /// <remarks/>
        public void sendProdImageAsync(object userState) {
            if ((this.sendProdImageOperationCompleted == null)) {
                this.sendProdImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendProdImageOperationCompleted);
            }
            this.InvokeAsync("sendProdImage", new object[0], this.sendProdImageOperationCompleted, userState);
        }
        
        private void OnsendProdImageOperationCompleted(object arg) {
            if ((this.sendProdImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendProdImageCompleted(this, new sendProdImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendWhish([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username) {
            object[] results = this.Invoke("sendWhish", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendWhishAsync(string username) {
            this.sendWhishAsync(username, null);
        }
        
        /// <remarks/>
        public void sendWhishAsync(string username, object userState) {
            if ((this.sendWhishOperationCompleted == null)) {
                this.sendWhishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendWhishOperationCompleted);
            }
            this.InvokeAsync("sendWhish", new object[] {
                        username}, this.sendWhishOperationCompleted, userState);
        }
        
        private void OnsendWhishOperationCompleted(object arg) {
            if ((this.sendWhishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendWhishCompleted(this, new sendWhishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendCartInfo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user) {
            object[] results = this.Invoke("sendCartInfo", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendCartInfoAsync(string user) {
            this.sendCartInfoAsync(user, null);
        }
        
        /// <remarks/>
        public void sendCartInfoAsync(string user, object userState) {
            if ((this.sendCartInfoOperationCompleted == null)) {
                this.sendCartInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendCartInfoOperationCompleted);
            }
            this.InvokeAsync("sendCartInfo", new object[] {
                        user}, this.sendCartInfoOperationCompleted, userState);
        }
        
        private void OnsendCartInfoOperationCompleted(object arg) {
            if ((this.sendCartInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendCartInfoCompleted(this, new sendCartInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string removeFromWhish([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string code) {
            object[] results = this.Invoke("removeFromWhish", new object[] {
                        user,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void removeFromWhishAsync(string user, string code) {
            this.removeFromWhishAsync(user, code, null);
        }
        
        /// <remarks/>
        public void removeFromWhishAsync(string user, string code, object userState) {
            if ((this.removeFromWhishOperationCompleted == null)) {
                this.removeFromWhishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveFromWhishOperationCompleted);
            }
            this.InvokeAsync("removeFromWhish", new object[] {
                        user,
                        code}, this.removeFromWhishOperationCompleted, userState);
        }
        
        private void OnremoveFromWhishOperationCompleted(object arg) {
            if ((this.removeFromWhishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeFromWhishCompleted(this, new removeFromWhishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string removeFromCart([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string code) {
            object[] results = this.Invoke("removeFromCart", new object[] {
                        user,
                        code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void removeFromCartAsync(string user, string code) {
            this.removeFromCartAsync(user, code, null);
        }
        
        /// <remarks/>
        public void removeFromCartAsync(string user, string code, object userState) {
            if ((this.removeFromCartOperationCompleted == null)) {
                this.removeFromCartOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveFromCartOperationCompleted);
            }
            this.InvokeAsync("removeFromCart", new object[] {
                        user,
                        code}, this.removeFromCartOperationCompleted, userState);
        }
        
        private void OnremoveFromCartOperationCompleted(object arg) {
            if ((this.removeFromCartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeFromCartCompleted(this, new removeFromCartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendArbolB() {
            object[] results = this.Invoke("sendArbolB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendArbolBAsync() {
            this.sendArbolBAsync(null);
        }
        
        /// <remarks/>
        public void sendArbolBAsync(object userState) {
            if ((this.sendArbolBOperationCompleted == null)) {
                this.sendArbolBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendArbolBOperationCompleted);
            }
            this.InvokeAsync("sendArbolB", new object[0], this.sendArbolBOperationCompleted, userState);
        }
        
        private void OnsendArbolBOperationCompleted(object arg) {
            if ((this.sendArbolBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendArbolBCompleted(this, new sendArbolBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sale([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user) {
            object[] results = this.Invoke("sale", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void saleAsync(string user) {
            this.saleAsync(user, null);
        }
        
        /// <remarks/>
        public void saleAsync(string user, object userState) {
            if ((this.saleOperationCompleted == null)) {
                this.saleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaleOperationCompleted);
            }
            this.InvokeAsync("sale", new object[] {
                        user}, this.saleOperationCompleted, userState);
        }
        
        private void OnsaleOperationCompleted(object arg) {
            if ((this.saleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saleCompleted(this, new saleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendHashGraph() {
            object[] results = this.Invoke("sendHashGraph", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendHashGraphAsync() {
            this.sendHashGraphAsync(null);
        }
        
        /// <remarks/>
        public void sendHashGraphAsync(object userState) {
            if ((this.sendHashGraphOperationCompleted == null)) {
                this.sendHashGraphOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendHashGraphOperationCompleted);
            }
            this.InvokeAsync("sendHashGraph", new object[0], this.sendHashGraphOperationCompleted, userState);
        }
        
        private void OnsendHashGraphOperationCompleted(object arg) {
            if ((this.sendHashGraphCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendHashGraphCompleted(this, new sendHashGraphCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string report1([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fFecha, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fValor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fusuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechafin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string valor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario) {
            object[] results = this.Invoke("report1", new object[] {
                        fFecha,
                        fValor,
                        fusuario,
                        fechaIni,
                        fechafin,
                        valor,
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void report1Async(string fFecha, string fValor, string fusuario, string fechaIni, string fechafin, string valor, string usuario) {
            this.report1Async(fFecha, fValor, fusuario, fechaIni, fechafin, valor, usuario, null);
        }
        
        /// <remarks/>
        public void report1Async(string fFecha, string fValor, string fusuario, string fechaIni, string fechafin, string valor, string usuario, object userState) {
            if ((this.report1OperationCompleted == null)) {
                this.report1OperationCompleted = new System.Threading.SendOrPostCallback(this.Onreport1OperationCompleted);
            }
            this.InvokeAsync("report1", new object[] {
                        fFecha,
                        fValor,
                        fusuario,
                        fechaIni,
                        fechafin,
                        valor,
                        usuario}, this.report1OperationCompleted, userState);
        }
        
        private void Onreport1OperationCompleted(object arg) {
            if ((this.report1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.report1Completed(this, new report1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string report2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaFin) {
            object[] results = this.Invoke("report2", new object[] {
                        fechaIni,
                        fechaFin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void report2Async(string fechaIni, string fechaFin) {
            this.report2Async(fechaIni, fechaFin, null);
        }
        
        /// <remarks/>
        public void report2Async(string fechaIni, string fechaFin, object userState) {
            if ((this.report2OperationCompleted == null)) {
                this.report2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onreport2OperationCompleted);
            }
            this.InvokeAsync("report2", new object[] {
                        fechaIni,
                        fechaFin}, this.report2OperationCompleted, userState);
        }
        
        private void Onreport2OperationCompleted(object arg) {
            if ((this.report2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.report2Completed(this, new report2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string report3([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaIni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaFin) {
            object[] results = this.Invoke("report3", new object[] {
                        fechaIni,
                        fechaFin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void report3Async(string fechaIni, string fechaFin) {
            this.report3Async(fechaIni, fechaFin, null);
        }
        
        /// <remarks/>
        public void report3Async(string fechaIni, string fechaFin, object userState) {
            if ((this.report3OperationCompleted == null)) {
                this.report3OperationCompleted = new System.Threading.SendOrPostCallback(this.Onreport3OperationCompleted);
            }
            this.InvokeAsync("report3", new object[] {
                        fechaIni,
                        fechaFin}, this.report3OperationCompleted, userState);
        }
        
        private void Onreport3OperationCompleted(object arg) {
            if ((this.report3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.report3Completed(this, new report3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string graphAvlTree() {
            object[] results = this.Invoke("graphAvlTree", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void graphAvlTreeAsync() {
            this.graphAvlTreeAsync(null);
        }
        
        /// <remarks/>
        public void graphAvlTreeAsync(object userState) {
            if ((this.graphAvlTreeOperationCompleted == null)) {
                this.graphAvlTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngraphAvlTreeOperationCompleted);
            }
            this.InvokeAsync("graphAvlTree", new object[0], this.graphAvlTreeOperationCompleted, userState);
        }
        
        private void OngraphAvlTreeOperationCompleted(object arg) {
            if ((this.graphAvlTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.graphAvlTreeCompleted(this, new graphAvlTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string graphAdList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string username) {
            object[] results = this.Invoke("graphAdList", new object[] {
                        username});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void graphAdListAsync(string username) {
            this.graphAdListAsync(username, null);
        }
        
        /// <remarks/>
        public void graphAdListAsync(string username, object userState) {
            if ((this.graphAdListOperationCompleted == null)) {
                this.graphAdListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngraphAdListOperationCompleted);
            }
            this.InvokeAsync("graphAdList", new object[] {
                        username}, this.graphAdListOperationCompleted, userState);
        }
        
        private void OngraphAdListOperationCompleted(object arg) {
            if ((this.graphAdListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.graphAdListCompleted(this, new graphAdListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string searchProduct([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int Code) {
            object[] results = this.Invoke("searchProduct", new object[] {
                        Code});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void searchProductAsync(int Code) {
            this.searchProductAsync(Code, null);
        }
        
        /// <remarks/>
        public void searchProductAsync(int Code, object userState) {
            if ((this.searchProductOperationCompleted == null)) {
                this.searchProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchProductOperationCompleted);
            }
            this.InvokeAsync("searchProduct", new object[] {
                        Code}, this.searchProductOperationCompleted, userState);
        }
        
        private void OnsearchProductOperationCompleted(object arg) {
            if ((this.searchProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchProductCompleted(this, new searchProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://com/", ResponseNamespace="http://com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sendWhishGraph([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string user) {
            object[] results = this.Invoke("sendWhishGraph", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sendWhishGraphAsync(string user) {
            this.sendWhishGraphAsync(user, null);
        }
        
        /// <remarks/>
        public void sendWhishGraphAsync(string user, object userState) {
            if ((this.sendWhishGraphOperationCompleted == null)) {
                this.sendWhishGraphOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendWhishGraphOperationCompleted);
            }
            this.InvokeAsync("sendWhishGraph", new object[] {
                        user}, this.sendWhishGraphOperationCompleted, userState);
        }
        
        private void OnsendWhishGraphOperationCompleted(object arg) {
            if ((this.sendWhishGraphCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendWhishGraphCompleted(this, new sendWhishGraphCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void receiveMessageCompletedEventHandler(object sender, receiveMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class receiveMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal receiveMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendCarritoGraphCompletedEventHandler(object sender, sendCarritoGraphCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendCarritoGraphCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendCarritoGraphCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void valUserCompletedEventHandler(object sender, valUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class valUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal valUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendProdCodeCompletedEventHandler(object sender, sendProdCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendProdCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendProdCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SendProdNameCompletedEventHandler(object sender, SendProdNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendProdNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendProdNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendProdBrandCompletedEventHandler(object sender, sendProdBrandCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendProdBrandCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendProdBrandCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendProdPriceCompletedEventHandler(object sender, sendProdPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendProdPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendProdPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendProdImageCompletedEventHandler(object sender, sendProdImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendProdImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendProdImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendWhishCompletedEventHandler(object sender, sendWhishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendWhishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendWhishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendCartInfoCompletedEventHandler(object sender, sendCartInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendCartInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendCartInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void removeFromWhishCompletedEventHandler(object sender, removeFromWhishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeFromWhishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeFromWhishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void removeFromCartCompletedEventHandler(object sender, removeFromCartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeFromCartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeFromCartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendArbolBCompletedEventHandler(object sender, sendArbolBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendArbolBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendArbolBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void saleCompletedEventHandler(object sender, saleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendHashGraphCompletedEventHandler(object sender, sendHashGraphCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendHashGraphCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendHashGraphCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void report1CompletedEventHandler(object sender, report1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class report1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal report1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void report2CompletedEventHandler(object sender, report2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class report2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal report2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void report3CompletedEventHandler(object sender, report3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class report3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal report3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void graphAvlTreeCompletedEventHandler(object sender, graphAvlTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class graphAvlTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal graphAvlTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void graphAdListCompletedEventHandler(object sender, graphAdListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class graphAdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal graphAdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void searchProductCompletedEventHandler(object sender, searchProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sendWhishGraphCompletedEventHandler(object sender, sendWhishGraphCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendWhishGraphCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendWhishGraphCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591